// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwkrstvjdgrtffmeauhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3a3JzdHZqZGdydGZmbWVhdWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDIzNzAsImV4cCI6MjA2MTMxODM3MH0.Akm3HhKAF_oT2d8tJSYuChKZnlIGBAjNFrM1ncROJVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);